rocky now working with tail and watch

diff --git a/opt_bob/rocky.sh.j2 b/opt_bob/rocky.sh.j2
--- a/opt_bob/rocky.sh.j2
+++ b/opt_bob/rocky.sh.j2
@@ -1,34 +1,39 @@
 #!/bin/sh
 
-echo -e "\n\n\e[36mDoing a build of ROCKY ...\e[0m"
+INFO='\e[36m'
+WARN='\e[32m'
+ERROR='\e[31m'
+END='\e[0m'
+
+echo -e "\n\n${INFO}Doing a build of ROCKY ...${END}"
 
 cd /tmp
 wget http://{{bob_listen_address}}/images/{{rocky_image_file}}.raw.gz
 
-echo -e "\n\n\e[36mPlease wait while image is written to {{disk}} ...\e[0m"
+echo -e "\n\n${INFO}Please wait while image is written to {{disk}} ...${END}"
 gunzip < {{rocky_image_file}}.raw.gz | dd of={{disk}} bs=4M
+
+# We seem to be having issues with sda1 appearing
 partprobe {{disk}}
+cd /dev
+[[ -e {{disk}}1 ]] || { echo -e "${WARN}No {{disk}}1 device => Trying to create ${END}"; mknod {{disk}}1 b 8 1; }
+[[ -e {{disk}}1 ]] || { echo -e "${ERROR}Device {{disk}}1 still doesn't exist${END}"; exit 1; }
 
 ## Cloud stuff
-echo -e "\n\n\e[36mConfiguring cloud-init ...\e[0m"
-mkdosfs -n CIDATA {{disk}}1
-mount -t vfat {{disk}}1 /mnt
+echo -e "\n\n${INFO}Configuring cloud-init ...${END}"
+mkdosfs -n CIDATA {{disk}}1 || { echo -e "${ERROR}FAILED to make filesystem on {{disk}}1${END}"; exit 1; }
+#
+mount -t vfat {{disk}}1 /mnt || { echo -e "${ERROR}FAILED to mount {{disk}}1${END}"; exit 1; }
 cd /mnt
 
-wget http://{{bob_listen_address}}/builder/meta-data
-wget http://{{bob_listen_address}}/builder/user-data
+wget http://{{bob_listen_address}}/builder/meta-{{mac}} -O meta-data
+wget http://{{bob_listen_address}}/builder/user-{{mac}} -O user-data
 
-wget http://{{bob_listen_address}}/wendy/api/complete/{{mac}}
+wget http://{{bob_listen_address}}/wendy/api/complete/{{mac}} -O /dev/null
 
-echo -e "\n\nSleeping 5 ..."
-sleep 1
-echo "Sleeping 4 ..."
-sleep 1
-echo "Sleeping 3 ..."
-sleep 1
-echo "Sleeping 2 ..."
-sleep 1
-echo "Sleeping 1 ..."
-sleep 1
-
+echo -e "\n\nSleeping 5 ..."; sleep 1
+echo "Sleeping 4 ..."; sleep 1
+echo "Sleeping 3 ..."; sleep 1
+echo "Sleeping 2 ..."; sleep 1
+echo "Sleeping 1 ..."; sleep 1
 reboot
