fixed doing a build on a dirty disk

diff --git a/opt_bob/templates/fedora.sh.j2 b/opt_bob/templates/fedora.sh.j2
--- a/opt_bob/templates/fedora.sh.j2
+++ b/opt_bob/templates/fedora.sh.j2
@@ -1,3 +1,37 @@
 #!/bin/sh
 
-echo "Doing a build of FEDORA ..."
+INFO='\e[36m'
+WARN='\e[32m'
+ERROR='\e[31m'
+END='\e[0m'
+
+echo -e "\n\n${INFO}Doing a build of FEDORA ...${END}"
+# Clean the disk first
+dd if=/dev/zero of={{disk}} bs=8M count=8
+partprobe {{disk}}
+
+cd /tmp
+wget http://{{bob_listen_address}}/images/{{fedora_image_file}}.raw.gz
+
+echo -e "\n\n${INFO}Please wait while image is written to {{disk}} ...${END}"
+gunzip < {{fedora_image_file}}.raw.gz | dd of={{disk}} bs=4M
+partprobe {{disk}}
+
+## Cloud stuff
+echo -e "\n\n${INFO}Configuring cloud-init ...${END}"
+mkdosfs -n CIDATA {{disk}}1 || { echo -e "${ERROR}FAILED to make filesystem on {{disk}}1${END}"; exit 1; }
+mount -t vfat {{disk}}1 /mnt || { echo -e "${ERROR}FAILED to mount {{disk}}1${END}"; exit 1; }
+
+cd /mnt
+wget http://{{bob_listen_address}}/build/meta-{{mac}} -O meta-data
+wget http://{{bob_listen_address}}/build/user-{{mac}} -O user-data
+
+# Notify Completion and count down to reboot
+wget http://{{bob_listen_address}}/wendy/api/complete/{{mac}} -O /dev/null
+
+echo -e "\n\nSleeping 5 ..."; sleep 1
+echo "Sleeping 4 ..."; sleep 1
+echo "Sleeping 3 ..."; sleep 1
+echo "Sleeping 2 ..."; sleep 1
+echo "Sleeping 1 ..."; sleep 1
+reboot
